services:
  - type: web
    name: your-bot-name
    env: python
    runtime: python-3.12.0  # Change from 3.13 to 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
